require 'forty/rake/task'
require 'forty'

sleep 10    # wait for docker-compose to start up the Postgres DB


# Prepare the example database to add schemas and tables.
#
pg = PG.connect(
    host: 'postgres_demo_db',
    port: 5432,
    user: ENV['SOME_APP_POSTGRES_USER'],
    password: ENV['SOME_APP_POSTGRES_PASSWORD'],
    dbname: ENV['SOME_APP_POSTGRES_DB'],
)

Forty.configuration.logger.info("Create example schemas and tables")
pg.exec("create schema if not exists some_schema;")
pg.exec("create schema if not exists another_schema;")
pg.exec("create table if not exists some_schema.some_table (id int);")
pg.exec("create table if not exists another_schema.another_table (id int);")
pg.exec("create user this_user_should_not_exist;")


# Forty configuration
#
Forty.configure do |config|
  config.master_username = ENV['SOME_APP_POSTGRES_USER']
  config.schemas = ['some_schema', 'another_schema']
  config.acl_file = 'acl.json'
  config.logger.level = ::Logger::INFO
end

Forty.database do |db|
  db.name = 'PostgresDemo' # optional, used when sending mails to DB users
  db.host = 'postgres_demo_db' # DNS provided by docker-compose
  db.port = 5432
  db.user = ENV['SOME_APP_POSTGRES_USER']
  db.password = ENV['SOME_APP_POSTGRES_PASSWORD']
  db.database = ENV['SOME_APP_POSTGRES_DB']
end

Forty.mailer do |mail|
  mail.smtp_address = ENV['FORTY_MAIL_SMTP_ADDRESS']
  mail.smtp_host = ENV['FORTY_MAIL_SMTP_HOST']
  mail.smtp_port = ENV['FORTY_MAIL_SMTP_PORT']
  mail.smtp_username = ENV['FORTY_MAIL_SMTP_USERNAME']
  mail.smtp_password = ENV['FORTY_MAIL_SMTP_PASSWORD']
  mail.smtp_authentication = :login
  mail.smtp_encryption = :tls
  mail.templates = { user_created: 'mail_template_user_created.erb' }
  mail.enabled = false # false because this config is just for demonstration purposes; set to true in production!
end
